# Generated by Django 3.1.4 on 2020-12-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='marcaid',
        ),
    ]
