# Generated by Django 3.1.4 on 2020-12-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_remove_marca_marcaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dpi', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to=None)),
            ],
        ),
    ]
